### ISSUE TITLE
Use image comparison as a dependency. 

### ISSUE THREAD

**Issue by romankh3** [KhaldAttya/Aeye#1]
Hello @khaldattya. I’ve seen that you’re using image-comparison  source code for your project. I have published image-comparison to Maven Central and you can add it as a dependency. 
```
 <dependency>
       <groupId>com.github.romankh3</groupId>
       <artifactId>image-comparison</artifactId>
       <version>3.1.1</version>
   </dependency>
```

It can help you to be up-to-date with all the improvements

**Comment by KhaldAttya** [comment]
Hello @romankh3 Thank you so much for your comment, I was going to do so. but I had trouble creating a fat jar (for local need) so I ended up using it like this( as initial commit) but I am planning to put my work on maven and use your library as dependency. Thanks so much for your comment again and just for a note I added that I am depending on image-comparison in my readme file.
Great work what you've done. keep it up

**Comment by romankh3** [comment]
Hello, @KhaldAttya!
I have added [new Pull-Request](https://github.com/KhaldAttya/Aeye/pull/2) with all the changes which are needed to do to migrate your project to using `image-comparison` as a dependency in `pom.xml`.

Best regards,
Roman.

**Comment by romankh3** [comment]
Fat jar you can generate as it was described in README or download it from [BINTRAY](https://bintray.com/romankh3/image-comparison/download_file?file_path=com%2Fgithub%2Fromankh3%2Fimage-comparison%2F3.1.1%2Fimage-comparison-3.1.1.jar).

Best regards,
Roman.

**Comment by KhaldAttya** [comment]
> Fat jar you can generate as it was described in README or download it from [BINTRAY](https://bintray.com/romankh3/image-comparison/download_file?file_path=com%2Fgithub%2Fromankh3%2Fimage-comparison%2F3.1.1%2Fimage-comparison-3.1.1.jar).
> 
> Best regards,
> Roman.

Great Thanks Roman

**Comment by romankh3** [comment]
@KhaldAttya, If it's not hard for you - please, star my project. It will help people know about them.

**Comment by KhaldAttya** [comment]
Done 👍

**Comment by KhaldAttya** [comment]
I might want to add some contributions to image-comparison so it would serve actual mobile visual testing needs based on challenges I might face I will put that on mind and PR whenever I make changes so you may review them.

Best Regards
Khaled

**Comment by romankh3** [comment]
> I might want to add some contributions to image-comparison so it would serve actual mobile visual testing needs based on challenges


Please, see my contributions page before making changes.
the first step is to discuss changes in the issue.

Best regards,
Roman.
